// ─── DATA ────────────────────────────────────────────────────────────────────
// plural: "—" = kein Plural (uncountable / no standard plural form)
export type Article = 'der' | 'die' | 'das'

export interface Noun {
  singular: string
  english: string
  article: Article
  plural: string
  category: string
  note: string
  // A1 example sentence using the noun (with its article) + its English
  // translation. Required: the backfill is complete, so the compiler now forces
  // every noun to carry both.
  example: string
  translation: string
}

export const nounData: Noun[] = [

  // ── Familie ────────────────────────────────────────────────────────────────
  {
    singular: "Vater",      english: "father",              article: "der", plural: "Väter",
    example: "Mein Vater arbeitet viel.", translation: "My father works a lot.",
    category: "Familie",
    note: "Umlaut only — vowel -a- becomes -ä-. Same pattern as Mutter, Bruder, Großvater.",
  },
  {
    singular: "Mutter",     english: "mother",              article: "die", plural: "Mütter",
    example: "Meine Mutter kocht gern.", translation: "My mother likes cooking.",
    category: "Familie",
    note: "Umlaut only. Note: die Eltern (parents) exists only in the plural — there is no singular.",
  },
  {
    singular: "Sohn",       english: "son",                 article: "der", plural: "Söhne",
    example: "Mein Sohn ist fünf Jahre alt.", translation: "My son is five years old.",
    category: "Familie",
    note: "Umlaut + -e ending. A very common masculine plural pattern.",
  },
  {
    singular: "Tochter",    english: "daughter",            article: "die", plural: "Töchter",
    example: "Meine Tochter geht zur Schule.", translation: "My daughter goes to school.",
    category: "Familie",
    note: "Umlaut only — same pattern as Mutter and Schwester.",
  },
  {
    singular: "Bruder",     english: "brother",             article: "der", plural: "Brüder",
    example: "Mein Bruder spielt Fußball.", translation: "My brother plays football.",
    category: "Familie",
    note: "Umlaut only. Contrast with die Schwester → Schwestern (no umlaut, -n ending).",
  },
  {
    singular: "Schwester",  english: "sister",              article: "die", plural: "Schwestern",
    example: "Meine Schwester wohnt in Berlin.", translation: "My sister lives in Berlin.",
    category: "Familie",
    note: "No umlaut — just adds -n. Feminine nouns very rarely take an umlaut in the plural.",
  },
  {
    singular: "Mann",       english: "man / husband",       article: "der", plural: "Männer",
    example: "Der Mann trinkt Kaffee.", translation: "The man is drinking coffee.",
    category: "Familie",
    note: "Umlaut + -er ending. Also means husband in context: mein Mann.",
  },
  {
    singular: "Frau",       english: "woman / wife",        article: "die", plural: "Frauen",
    example: "Die Frau kauft Brot.", translation: "The woman is buying bread.",
    category: "Familie",
    note: "No umlaut, adds -en. Also means wife in context: meine Frau.",
  },
  {
    singular: "Kind",       english: "child",               article: "das", plural: "Kinder",
    example: "Das Kind spielt im Garten.", translation: "The child is playing in the garden.",
    category: "Familie",
    note: "-er ending, no umlaut. One of the most essential neuter nouns in German.",
  },
  {
    singular: "Großvater",  english: "grandfather",         article: "der", plural: "Großväter",
    example: "Mein Großvater wohnt auf dem Land.", translation: "My grandfather lives in the countryside.",
    category: "Familie",
    note: "Compound: groß + Vater. The plural follows Vater → Väter.",
  },
  {
    singular: "Großmutter", english: "grandmother",         article: "die", plural: "Großmütter",
    example: "Meine Großmutter backt einen Kuchen.", translation: "My grandmother is baking a cake.",
    category: "Familie",
    note: "Compound: groß + Mutter. Follows Mutter → Mütter.",
  },
  {
    singular: "Onkel",      english: "uncle",               article: "der", plural: "Onkel",
    example: "Mein Onkel wohnt in Hamburg.", translation: "My uncle lives in Hamburg.",
    category: "Familie",
    note: "No change in the plural! Many masculine nouns ending in -el stay the same.",
  },
  {
    singular: "Tante",      english: "aunt",                article: "die", plural: "Tanten",
    example: "Meine Tante trinkt gern Tee.", translation: "My aunt likes drinking tea.",
    category: "Familie",
    note: "Adds -n. Borrowed from French tante.",
  },
  {
    singular: "Cousin",     english: "male cousin",         article: "der", plural: "Cousins",
    example: "Mein Cousin ist sehr nett.", translation: "My (male) cousin is very nice.",
    category: "Familie",
    note: "Borrowed from French — takes -s in the plural, like most foreign loanwords.",
  },
  {
    singular: "Cousine",    english: "female cousin",       article: "die", plural: "Cousinen",
    example: "Meine Cousine lernt Deutsch.", translation: "My (female) cousin is learning German.",
    category: "Familie",
    note: "Also from French. Note the -e ending for the feminine form.",
  },

  // ── Supermarkt ─────────────────────────────────────────────────────────────
  {
    singular: "Brot",       english: "bread",               article: "das", plural: "Brote",
    example: "Das Brot ist frisch.", translation: "The bread is fresh.",
    category: "Supermarkt",
    note: "Adds -e. A common pattern for many one-syllable neuter nouns.",
  },
  {
    singular: "Brötchen",   english: "bread roll",          article: "das", plural: "Brötchen",
    example: "Ich esse ein Brötchen.", translation: "I am eating a bread roll.",
    category: "Supermarkt",
    note: "No change — all -chen diminutives are unchanged in the plural.",
  },
  {
    singular: "Milch",      english: "milk",                article: "die", plural: "—",
    example: "Die Milch ist kalt.", translation: "The milk is cold.",
    category: "Supermarkt",
    note: "Uncountable. If counting servings, use: eine Tüte Milch (a carton of milk).",
  },
  {
    singular: "Käse",       english: "cheese",              article: "der", plural: "Käse",
    example: "Der Käse kommt aus der Schweiz.", translation: "The cheese comes from Switzerland.",
    category: "Supermarkt",
    note: "No change. Most masculine nouns ending in -e stay the same in the plural.",
  },
  {
    singular: "Fleisch",    english: "meat",                article: "das", plural: "—",
    example: "Ich esse kein Fleisch.", translation: "I don't eat meat.",
    category: "Supermarkt",
    note: "Uncountable. Use ein Stück Fleisch (a piece of meat) if you need to portion it.",
  },
  {
    singular: "Fisch",      english: "fish",                article: "der", plural: "Fische",
    example: "Der Fisch ist frisch.", translation: "The fish is fresh.",
    category: "Supermarkt",
    note: "Adds -e. As food: Ich esse Fisch. As animals: die Fische.",
  },
  {
    singular: "Ei",         english: "egg",                 article: "das", plural: "Eier",
    example: "Ich koche ein Ei.", translation: "I am boiling an egg.",
    category: "Supermarkt",
    note: "Adds -er. Common neuter plural pattern — same as Buch → Bücher, Kind → Kinder.",
  },
  {
    singular: "Butter",     english: "butter",              article: "die", plural: "—",
    example: "Die Butter ist im Kühlschrank.", translation: "The butter is in the fridge.",
    category: "Supermarkt",
    note: "Uncountable. Regional dialects sometimes use die Buttern but avoid it in standard German.",
  },
  {
    singular: "Joghurt",    english: "yogurt",              article: "der", plural: "Joghurts",
    example: "Ich esse einen Joghurt.", translation: "I am eating a yogurt.",
    category: "Supermarkt",
    note: "Takes -s — typical for foreign loanwords. Also das Joghurt in Austrian German.",
  },
  {
    singular: "Sandwich",   english: "sandwich",            article: "das", plural: "Sandwiches",
    example: "Ich mache ein Sandwich.", translation: "I am making a sandwich.",
    category: "Supermarkt",
    note: "English loanword — keeps the English plural. Also acceptable: die Sandwichs.",
  },
  {
    singular: "Wurst",      english: "sausage",             article: "die", plural: "Würste",
    example: "Die Wurst ist lecker.", translation: "The sausage is delicious.",
    category: "Supermarkt",
    note: "Umlaut + -e. One of the most iconic German food words!",
  },
  {
    singular: "Würstchen",  english: "small sausage",       article: "das", plural: "Würstchen",
    example: "Das Kind isst ein Würstchen.", translation: "The child is eating a small sausage.",
    category: "Supermarkt",
    note: "Diminutive of Wurst with -chen suffix → no plural change.",
  },
  {
    singular: "Apfel",      english: "apple",               article: "der", plural: "Äpfel",
    example: "Der Apfel ist rot.", translation: "The apple is red.",
    category: "Supermarkt",
    note: "Umlaut only — same pattern as Vater, Bruder, Mantel.",
  },
  {
    singular: "Banane",     english: "banana",              article: "die", plural: "Bananen",
    example: "Ich esse eine Banane.", translation: "I am eating a banana.",
    category: "Supermarkt",
    note: "Adds -n. Standard feminine -e noun plural.",
  },
  {
    singular: "Saft",       english: "juice",               article: "der", plural: "Säfte",
    example: "Ich trinke einen Saft.", translation: "I am drinking a juice.",
    category: "Supermarkt",
    note: "Umlaut + -e. Very common: masculine one-syllable nouns often follow this pattern.",
  },
  {
    singular: "Wasser",     english: "water",               article: "das", plural: "Wasser",
    example: "Ich trinke viel Wasser.", translation: "I drink a lot of water.",
    category: "Supermarkt",
    note: "No change as a substance. Countable for types or bottles: zwei Wasser, bitte.",
  },
  {
    singular: "Wein",       english: "wine",                article: "der", plural: "Weine",
    example: "Der Wein ist rot.", translation: "The wine is red.",
    category: "Supermarkt",
    note: "Adds -e. Simple and very regular.",
  },
  {
    singular: "Bier",       english: "beer",                article: "das", plural: "Biere",
    example: "Das Bier ist kalt.", translation: "The beer is cold.",
    category: "Supermarkt",
    note: "Adds -e. Zwei Biere, bitte! A common phrase at any Biergarten.",
  },
  {
    singular: "Kaffee",     english: "coffee",              article: "der", plural: "Kaffees",
    example: "Ich trinke einen Kaffee.", translation: "I am drinking a coffee.",
    category: "Supermarkt",
    note: "Adds -s — the loanword plural pattern. Also: einen Kaffee, bitte (ordering one coffee).",
  },
  {
    singular: "Tee",        english: "tea",                 article: "der", plural: "Tees",
    example: "Der Tee ist heiß.", translation: "The tea is hot.",
    category: "Supermarkt",
    note: "Adds -s — same loanword pattern as Kaffee. Borrowed via Dutch thee from Mandarin chá.",
  },

  // ── Zuhause ────────────────────────────────────────────────────────────────
  {
    singular: "Haus",       english: "house",               article: "das", plural: "Häuser",
    example: "Das Haus ist groß.", translation: "The house is big.",
    category: "Zuhause",
    note: "Umlaut + -er. One of the most common neuter nouns — every learner needs this one.",
  },
  {
    singular: "Wohnung",    english: "apartment / flat",    article: "die", plural: "Wohnungen",
    example: "Meine Wohnung ist klein.", translation: "My apartment is small.",
    category: "Zuhause",
    note: "Adds -en. Feminine nouns with the -ung suffix always take -en in the plural.",
  },
  {
    singular: "Zimmer",     english: "room",                article: "das", plural: "Zimmer",
    example: "Das Zimmer ist hell.", translation: "The room is bright.",
    category: "Zuhause",
    note: "No change. Neuter nouns ending in -er are unchanged in the plural.",
  },
  {
    singular: "Küche",      english: "kitchen",             article: "die", plural: "Küchen",
    example: "Die Küche ist neu.", translation: "The kitchen is new.",
    category: "Zuhause",
    note: "Adds -n. Also means cuisine: die deutsche Küche (German cuisine).",
  },
  {
    singular: "Badezimmer", english: "bathroom",            article: "das", plural: "Badezimmer",
    example: "Das Badezimmer ist oben.", translation: "The bathroom is upstairs.",
    category: "Zuhause",
    note: "Compound: das Bad + das Zimmer. Both parts neuter, result is unchanged in the plural.",
  },
  {
    singular: "Wohnzimmer", english: "living room",         article: "das", plural: "Wohnzimmer",
    example: "Wir sitzen im Wohnzimmer.", translation: "We are sitting in the living room.",
    category: "Zuhause",
    note: "Compound: wohnen (to live) + Zimmer. Unchanged in the plural.",
  },
  {
    singular: "Tisch",      english: "table",               article: "der", plural: "Tische",
    example: "Der Tisch ist aus Holz.", translation: "The table is made of wood.",
    category: "Zuhause",
    note: "Adds -e. A very regular masculine one-syllable noun.",
  },
  {
    singular: "Stuhl",      english: "chair",               article: "der", plural: "Stühle",
    example: "Der Stuhl ist bequem.", translation: "The chair is comfortable.",
    category: "Zuhause",
    note: "Umlaut + -e. Contrast with der Tisch → Tische (same ending, but no umlaut).",
  },
  {
    singular: "Bett",       english: "bed",                 article: "das", plural: "Betten",
    example: "Das Bett ist weich.", translation: "The bed is soft.",
    category: "Zuhause",
    note: "Adds -en. Common neuter noun.",
  },
  {
    singular: "Schrank",    english: "cupboard / wardrobe", article: "der", plural: "Schränke",
    example: "Der Schrank ist voll.", translation: "The cupboard is full.",
    category: "Zuhause",
    note: "Umlaut + -e. Der Kühlschrank (fridge) follows the exact same pattern.",
  },
  {
    singular: "Tür",        english: "door",                article: "die", plural: "Türen",
    example: "Die Tür ist offen.", translation: "The door is open.",
    category: "Zuhause",
    note: "Adds -en. Short feminine nouns often take -en in the plural.",
  },
  {
    singular: "Fenster",    english: "window",              article: "das", plural: "Fenster",
    example: "Das Fenster ist zu.", translation: "The window is closed.",
    category: "Zuhause",
    note: "No change. Neuter noun ending in -er.",
  },
  {
    singular: "Wand",       english: "wall",                article: "die", plural: "Wände",
    example: "Die Wand ist weiß.", translation: "The wall is white.",
    category: "Zuhause",
    note: "Umlaut + -e. Refers to an interior wall. An exterior/outdoor wall is die Mauer instead.",
  },
  {
    singular: "Treppe",     english: "stairs / staircase",  article: "die", plural: "Treppen",
    example: "Die Treppe ist steil.", translation: "The stairs are steep.",
    category: "Zuhause",
    note: "Adds -n. Regular feminine noun ending in -e.",
  },
  {
    singular: "Schlüssel",  english: "key",                 article: "der", plural: "Schlüssel",
    example: "Der Schlüssel liegt auf dem Tisch.", translation: "The key is on the table.",
    category: "Zuhause",
    note: "No change — masculine nouns ending in -el often stay the same (like Onkel).",
  },
  {
    singular: "Lampe",      english: "lamp",                article: "die", plural: "Lampen",
    example: "Ich mache die Lampe an.", translation: "I turn on the lamp.",
    category: "Zuhause",
    note: "Adds -n. Very regular feminine -e noun.",
  },
  {
    singular: "Sofa",          english: "sofa / couch",           article: "das", plural: "Sofas",
    example: "Ich sitze auf dem Sofa.", translation: "I am sitting on the sofa.",
    category: "Zuhause",
    note: "Adds -s — the loanword plural pattern. Italian origin via Arabic ṣuffa.",
  },
  {
    singular: "Regal",         english: "shelf / bookcase",       article: "das", plural: "Regale",
    example: "Die Bücher stehen im Regal.", translation: "The books are on the shelf.",
    category: "Zuhause",
    note: "Adds -e. Das Regal — neuter, not der or die. From Latin regalis (royal), via French. A common learner mistake is the gender!",
  },
  {
    singular: "Fernseher",     english: "television / TV",        article: "der", plural: "Fernseher",
    example: "Der Fernseher ist an.", translation: "The TV is on.",
    category: "Zuhause",
    note: "No change. Compound: fern (far) + sehen (to see) + -er (device suffix). Der Fernseher läuft (the TV is on).",
  },
  {
    singular: "Sessel",        english: "armchair",               article: "der", plural: "Sessel",
    example: "Opa sitzt im Sessel.", translation: "Grandpa is sitting in the armchair.",
    category: "Zuhause",
    note: "No change — masculine -el noun. Distinct from der Stuhl (upright chair): a Sessel is padded and comfortable.",
  },
  {
    singular: "Teppich",       english: "carpet / rug",           article: "der", plural: "Teppiche",
    example: "Der Teppich ist rot.", translation: "The carpet is red.",
    category: "Zuhause",
    note: "Adds -e. Der Teppichboden is wall-to-wall carpet. Der Teppich is a freestanding rug.",
  },
  {
    singular: "Schreibtisch",  english: "desk / writing table",   article: "der", plural: "Schreibtische",
    example: "Ich arbeite am Schreibtisch.", translation: "I work at the desk.",
    category: "Zuhause",
    note: "Adds -e. Compound: schreiben (to write) + Tisch (table). Am Schreibtisch sitzen (to sit at the desk).",
  },
  {
    singular: "Dusche",        english: "shower",                 article: "die", plural: "Duschen",
    example: "Die Dusche ist kaputt.", translation: "The shower is broken.",
    category: "Zuhause",
    note: "Adds -n. Also used as a verb: duschen (to shower). Ich dusche jeden Morgen.",
  },
  {
    singular: "Badewanne",     english: "bathtub",                article: "die", plural: "Badewannen",
    example: "Das Kind sitzt in der Badewanne.", translation: "The child is sitting in the bathtub.",
    category: "Zuhause",
    note: "Adds -n. Compound: das Bad (bath) + die Wanne (tub/basin). In der Badewanne liegen (to lie in the bath).",
  },
  {
    singular: "Waschbecken",   english: "sink / washbasin",       article: "das", plural: "Waschbecken",
    example: "Das Waschbecken ist sauber.", translation: "The washbasin is clean.",
    category: "Zuhause",
    note: "No change. Compound: waschen (to wash) + das Becken (basin). Neuter -en noun — unchanged in plural.",
  },
  {
    singular: "Toilette",      english: "toilet",                 article: "die", plural: "Toiletten",
    example: "Wo ist die Toilette?", translation: "Where is the toilet?",
    category: "Zuhause",
    note: "Adds -en. Borrowed from French toilette. Wo ist die Toilette? is essential A1 vocabulary!",
  },
  {
    singular: "Waschmaschine", english: "washing machine",        article: "die", plural: "Waschmaschinen",
    example: "Die Waschmaschine läuft.", translation: "The washing machine is running.",
    category: "Zuhause",
    note: "Adds -n. Compound: waschen + die Maschine. Die Wäsche waschen (to do the laundry) often pairs with this.",
  },
  {
    singular: "Elektrogerät",  english: "electrical appliance",   article: "das", plural: "Elektrogeräte",
    example: "Der Fernseher ist ein Elektrogerät.", translation: "The television is an electrical appliance.",
    category: "Zuhause",
    note: "Adds -e. Compound: elektro- + das Gerät (device/appliance). A useful umbrella term for all household electronics.",
  },

  // ── Tiere ──────────────────────────────────────────────────────────────────
  {
    singular: "Hund",       english: "dog",                 article: "der", plural: "Hunde",
    example: "Der Hund bellt laut.", translation: "The dog barks loudly.",
    category: "Tiere",
    note: "Adds -e. One of the first nouns every German learner meets.",
  },
  {
    singular: "Katze",      english: "cat",                 article: "die", plural: "Katzen",
    example: "Die Katze trinkt Milch.", translation: "The cat is drinking milk.",
    category: "Tiere",
    note: "Adds -n. Feminine nouns ending in -e almost always follow this pattern.",
  },
  {
    singular: "Vogel",      english: "bird",                article: "der", plural: "Vögel",
    example: "Der Vogel singt.", translation: "The bird is singing.",
    category: "Tiere",
    note: "Umlaut only — same pattern as der Apfel → Äpfel. Vowel -o- becomes -ö-.",
  },
  {
    singular: "Pferd",      english: "horse",               article: "das", plural: "Pferde",
    example: "Das Pferd läuft schnell.", translation: "The horse runs fast.",
    category: "Tiere",
    note: "Adds -e. Note the gender: das Pferd (neuter), not der or die.",
  },
  {
    singular: "Kuh",        english: "cow",                 article: "die", plural: "Kühe",
    example: "Die Kuh steht auf der Wiese.", translation: "The cow is standing in the meadow.",
    category: "Tiere",
    note: "Umlaut + -e. Short feminine noun.",
  },
  {
    singular: "Schwein",    english: "pig",                 article: "das", plural: "Schweine",
    example: "Das Schwein ist rosa.", translation: "The pig is pink.",
    category: "Tiere",
    note: "Adds -e. Also heard colloquially in Schwein gehabt! (got lucky!).",
  },
  {
    singular: "Löwe",       english: "lion",                article: "der", plural: "Löwen",
    example: "Der Löwe ist stark.", translation: "The lion is strong.",
    category: "Tiere",
    note: "Adds -n. A weak masculine noun (N-Deklination) — takes -n/-en in all cases except nominative.",
  },
  {
    singular: "Bär",        english: "bear",                article: "der", plural: "Bären",
    example: "Der Bär schläft im Winter.", translation: "The bear sleeps in winter.",
    category: "Tiere",
    note: "Adds -en. Also a weak masculine noun. The bear is the symbol of Berlin.",
  },
  {
    singular: "Maus",       english: "mouse",               article: "die", plural: "Mäuse",
    example: "Die Maus ist klein.", translation: "The mouse is small.",
    category: "Tiere",
    note: "Umlaut + -e. Also the computer mouse: die Computermaus → die Computermäuse.",
  },
  {
    singular: "Affe",       english: "monkey / ape",        article: "der", plural: "Affen",
    example: "Der Affe klettert auf den Baum.", translation: "The monkey climbs up the tree.",
    category: "Tiere",
    note: "Adds -n. Another weak masculine noun.",
  },
  {
    singular: "Schlange",   english: "snake",               article: "die", plural: "Schlangen",
    example: "Die Schlange ist lang.", translation: "The snake is long.",
    category: "Tiere",
    note: "Adds -n. Also means queue or line: in der Schlange stehen (to queue).",
  },
  {
    singular: "Elefant",    english: "elephant",            article: "der", plural: "Elefanten",
    example: "Der Elefant ist sehr groß.", translation: "The elephant is very big.",
    category: "Tiere",
    note: "Adds -en. Weak masculine noun.",
  },
  {
    singular: "Ente",       english: "duck",                article: "die", plural: "Enten",
    example: "Die Ente schwimmt im See.", translation: "The duck is swimming in the lake.",
    category: "Tiere",
    note: "Adds -n. Often heard at ponds: Enten füttern! (feeding the ducks).",
  },
  {
    singular: "Hase",       english: "rabbit / hare",       article: "der", plural: "Hasen",
    example: "Der Hase hat lange Ohren.", translation: "The rabbit has long ears.",
    category: "Tiere",
    note: "Adds -n. Weak masculine noun. The Easter Bunny is der Osterhase.",
  },

  // ── Kleidung ───────────────────────────────────────────────────────────────
  {
    singular: "Hemd",       english: "shirt",               article: "das", plural: "Hemden",
    example: "Das Hemd ist weiß.", translation: "The shirt is white.",
    category: "Kleidung",
    note: "Adds -en. Das Hemd is a dress shirt; das T-Shirt is the casual one.",
  },
  {
    singular: "Hose",       english: "trousers / pants",    article: "die", plural: "Hosen",
    example: "Die Hose ist zu eng.", translation: "The trousers are too tight.",
    category: "Kleidung",
    note: "Adds -n. Die Hose is grammatically singular in German — one pair, one noun.",
  },
  {
    singular: "Rock",       english: "skirt",               article: "der", plural: "Röcke",
    example: "Der Rock ist kurz.", translation: "The skirt is short.",
    category: "Kleidung",
    note: "Umlaut + -e. Also means music genre (der Rock) or a coat (archaic).",
  },
  {
    singular: "Jacke",      english: "jacket",              article: "die", plural: "Jacken",
    example: "Ich trage eine Jacke.", translation: "I am wearing a jacket.",
    category: "Kleidung",
    note: "Adds -n. Regular feminine -e noun.",
  },
  {
    singular: "Mantel",     english: "coat / overcoat",     article: "der", plural: "Mäntel",
    example: "Der Mantel ist warm.", translation: "The coat is warm.",
    category: "Kleidung",
    note: "Umlaut only — same pattern as Apfel and Vogel (short vowel + -el ending).",
  },
  {
    singular: "Schuh",      english: "shoe",                article: "der", plural: "Schuhe",
    example: "Der Schuh ist zu klein.", translation: "The shoe is too small.",
    category: "Kleidung",
    note: "Adds -e. Usually comes in pairs: die Schuhe.",
  },
  {
    singular: "Socke",      english: "sock",                article: "die", plural: "Socken",
    example: "Die Socke ist rot.", translation: "The sock is red.",
    category: "Kleidung",
    note: "Adds -n. Usually in pairs: ein Paar Socken.",
  },
  {
    singular: "Mütze",      english: "hat / beanie",        article: "die", plural: "Mützen",
    example: "Im Winter trage ich eine Mütze.", translation: "In winter I wear a beanie.",
    category: "Kleidung",
    note: "Adds -n. Specifically a knitted or soft hat — die Kappe is a baseball cap.",
  },
  {
    singular: "Kleid",      english: "dress",               article: "das", plural: "Kleider",
    example: "Das Kleid ist schön.", translation: "The dress is beautiful.",
    category: "Kleidung",
    note: "Adds -er. Plural die Kleider can also mean clothes in general.",
  },
  {
    singular: "Pullover",   english: "sweater / jumper",    article: "der", plural: "Pullover",
    example: "Der Pullover ist blau.", translation: "The sweater is blue.",
    category: "Kleidung",
    note: "No change — loanword ending in -er stays the same. From English pull-over.",
  },
  {
    singular: "Bluse",      english: "blouse",              article: "die", plural: "Blusen",
    example: "Die Bluse ist neu.", translation: "The blouse is new.",
    category: "Kleidung",
    note: "Adds -n. Borrowed from French blouse.",
  },
  {
    singular: "T-Shirt",    english: "T-shirt",             article: "das", plural: "T-Shirts",
    example: "Das T-Shirt ist zu groß.", translation: "The T-shirt is too big.",
    category: "Kleidung",
    note: "Adds -s — English loanword takes the English plural.",
  },

  // ── Körper ─────────────────────────────────────────────────────────────────
  {
    singular: "Kopf",       english: "head",                article: "der", plural: "Köpfe",
    example: "Mein Kopf tut weh.", translation: "My head hurts.",
    category: "Körper",
    note: "Umlaut + -e. Also means leader or top: der Bahnhofskopf (station end).",
  },
  {
    singular: "Auge",       english: "eye",                 article: "das", plural: "Augen",
    example: "Das Auge ist blau.", translation: "The eye is blue.",
    category: "Körper",
    note: "Adds -n. Das Auge is neuter but takes the -n plural — an exception to watch for.",
  },
  {
    singular: "Nase",       english: "nose",                article: "die", plural: "Nasen",
    example: "Meine Nase ist kalt.", translation: "My nose is cold.",
    category: "Körper",
    note: "Adds -n. Regular feminine -e noun.",
  },
  {
    singular: "Mund",       english: "mouth",               article: "der", plural: "Münder",
    example: "Der Mund ist offen.", translation: "The mouth is open.",
    category: "Körper",
    note: "Umlaut + -er. A less common plural pattern for masculine nouns.",
  },
  {
    singular: "Ohr",        english: "ear",                 article: "das", plural: "Ohren",
    example: "Das Ohr ist klein.", translation: "The ear is small.",
    category: "Körper",
    note: "Adds -en. Neuter noun with -en plural — another exception to note.",
  },
  {
    singular: "Arm",        english: "arm",                 article: "der", plural: "Arme",
    example: "Mein Arm ist lang.", translation: "My arm is long.",
    category: "Körper",
    note: "Adds -e. Very regular masculine noun.",
  },
  {
    singular: "Hand",       english: "hand",                article: "die", plural: "Hände",
    example: "Ich hebe die Hand.", translation: "I raise my hand.",
    category: "Körper",
    note: "Umlaut + -e. Die Hände is very common: Hände waschen! (wash your hands!).",
  },
  {
    singular: "Bein",       english: "leg",                 article: "das", plural: "Beine",
    example: "Ich stehe auf einem Bein.", translation: "I am standing on one leg.",
    category: "Körper",
    note: "Adds -e. Also means bone in some compounds: das Gebein.",
  },
  {
    singular: "Fuß",        english: "foot",                article: "der", plural: "Füße",
    example: "Ich gehe zu Fuß.", translation: "I go on foot.",
    category: "Körper",
    note: "Umlaut + -e. Common phrase: zu Fuß gehen (to go on foot).",
  },
  {
    singular: "Finger",     english: "finger",              article: "der", plural: "Finger",
    example: "Ich habe zehn Finger.", translation: "I have ten fingers.",
    category: "Körper",
    note: "No change. Masculine nouns ending in -er are almost always unchanged in the plural.",
  },
  {
    singular: "Bauch",      english: "belly / stomach",     article: "der", plural: "Bäuche",
    example: "Der Bauch tut weh.", translation: "The stomach hurts.",
    category: "Körper",
    note: "Umlaut + -e.",
  },
  {
    singular: "Gesicht",    english: "face",                article: "das", plural: "Gesichter",
    example: "Ich wasche mein Gesicht.", translation: "I am washing my face.",
    category: "Körper",
    note: "Adds -er. Same pattern as das Kind → Kinder and das Haus → Häuser.",
  },

  // ── Schule ─────────────────────────────────────────────────────────────────
  {
    singular: "Schule",       english: "school",                article: "die", plural: "Schulen",
    example: "Ich gehe zur Schule.", translation: "I go to school.",
    category: "Schule",
    note: "Adds -n. Die Schule also refers to the school building itself: Ich gehe zur Schule.",
  },
  {
    singular: "Lehrer",       english: "(male) teacher",        article: "der", plural: "Lehrer",
    example: "Der Lehrer erklärt die Grammatik.", translation: "The teacher explains the grammar.",
    category: "Schule",
    note: "No change — masculine nouns ending in -er are unchanged in the plural.",
  },
  {
    singular: "Lehrerin",     english: "(female) teacher",      article: "die", plural: "Lehrerinnen",
    example: "Die Lehrerin ist nett.", translation: "The (female) teacher is nice.",
    category: "Schule",
    note: "Adds -nen. The standard way to make a feminine job title: Lehrer → Lehrerin → Lehrerinnen.",
  },
  {
    singular: "Buch",         english: "book",                  article: "das", plural: "Bücher",
    example: "Das Buch ist interessant.", translation: "The book is interesting.",
    category: "Schule",
    note: "Umlaut + -er. Same pattern as das Haus → Häuser and das Fach → Fächer.",
  },
  {
    singular: "Heft",         english: "exercise book / notebook", article: "das", plural: "Hefte",
    example: "Ich schreibe ins Heft.", translation: "I write in the notebook.",
    category: "Schule",
    note: "Adds -e. Very common word — every German pupil carries several Hefte.",
  },
  {
    singular: "Stift",        english: "pen / pencil",          article: "der", plural: "Stifte",
    example: "Der Stift schreibt nicht.", translation: "The pen doesn't write.",
    category: "Schule",
    note: "Adds -e. Generic term for any writing instrument. Bleistift is specifically a pencil.",
  },
  {
    singular: "Tafel",        english: "board (black- or white-)", article: "die", plural: "Tafeln",
    example: "Die Tafel ist grün.", translation: "The board is green.",
    category: "Schule",
    note: "Adds -n. Also means bar of chocolate: eine Tafel Schokolade.",
  },
  {
    singular: "Rucksack",     english: "backpack / rucksack",   article: "der", plural: "Rucksäcke",
    example: "Mein Rucksack ist schwer.", translation: "My backpack is heavy.",
    category: "Schule",
    note: "Umlaut + -e. Compound: der Rücken (back) + der Sack (bag).",
  },
  {
    singular: "Klasse",       english: "class / year group",    article: "die", plural: "Klassen",
    example: "Die Klasse ist laut.", translation: "The class is loud.",
    category: "Schule",
    note: "Adds -n. Also means classroom in context: Wir gehen in die Klasse.",
  },
  {
    singular: "Hausaufgabe",  english: "homework (one task)",   article: "die", plural: "Hausaufgaben",
    example: "Ich vergesse die Hausaufgabe.", translation: "I forget the homework.",
    category: "Schule",
    note: "Adds -n. Compound: das Haus + die Aufgabe (task). Usually used in the plural: die Hausaufgaben.",
  },
  {
    singular: "Prüfung",      english: "exam / test",           article: "die", plural: "Prüfungen",
    example: "Morgen habe ich eine Prüfung.", translation: "Tomorrow I have an exam.",
    category: "Schule",
    note: "Adds -en. Feminine -ung nouns always take -en in the plural — same as Wohnung, Besprechung.",
  },
  {
    singular: "Note",         english: "grade / mark",          article: "die", plural: "Noten",
    example: "Ich bekomme eine gute Note.", translation: "I get a good grade.",
    category: "Schule",
    note: "Adds -n. Also means musical note. German grades run 1 (very good) to 6 (unsatisfactory).",
  },
  {
    singular: "Fach",         english: "subject",               article: "das", plural: "Fächer",
    example: "Deutsch ist mein bestes Fach.", translation: "German is my best subject.",
    category: "Schule",
    note: "Umlaut + -er. Also means compartment or drawer. Mein Lieblingsfach is my favourite subject.",
  },
  {
    singular: "Pause",        english: "break / recess",        article: "die", plural: "Pausen",
    example: "Wir machen eine Pause.", translation: "We are taking a break.",
    category: "Schule",
    note: "Adds -n. Also used at work and in music: eine Pause machen (to take a break).",
  },

  // ── Arbeit ─────────────────────────────────────────────────────────────────
  {
    singular: "Büro",         english: "office",                article: "das", plural: "Büros",
    example: "Ich gehe ins Büro.", translation: "I am going to the office.",
    category: "Arbeit",
    note: "Adds -s — loanword plural. Borrowed from French bureau. Ins Büro gehen (to go to the office).",
  },
  {
    singular: "Beruf",        english: "profession / occupation", article: "der", plural: "Berufe",
    example: "Was sind Sie von Beruf?", translation: "What is your profession?",
    category: "Arbeit",
    note: "Adds -e. Was sind Sie von Beruf? (What do you do for a living?) is a key A1 phrase.",
  },
  {
    singular: "Chef",         english: "boss / manager",        article: "der", plural: "Chefs",
    example: "Mein Chef ist streng.", translation: "My boss is strict.",
    category: "Arbeit",
    note: "Adds -s — loanword plural. Borrowed from French chef. Die Chefin is the female form.",
  },
  {
    singular: "Kollege",      english: "(male) colleague",      article: "der", plural: "Kollegen",
    example: "Mein Kollege hilft mir.", translation: "My colleague helps me.",
    category: "Arbeit",
    note: "Adds -n. A weak masculine noun (N-Deklination). Die Kollegin is the female form.",
  },
  {
    singular: "Kollegin",     english: "(female) colleague",    article: "die", plural: "Kolleginnen",
    example: "Meine Kollegin ist krank.", translation: "My (female) colleague is sick.",
    category: "Arbeit",
    note: "Adds -nen. Standard feminine form — same pattern as Lehrerin → Lehrerinnen.",
  },
  {
    singular: "Gehalt",       english: "salary / wage",         article: "das", plural: "Gehälter",
    example: "Mein Gehalt ist gut.", translation: "My salary is good.",
    category: "Arbeit",
    note: "Umlaut + -er. Distinct from der Lohn (hourly wage): Gehalt is a fixed monthly salary.",
  },
  {
    singular: "Besprechung",  english: "meeting / discussion",  article: "die", plural: "Besprechungen",
    example: "Die Besprechung dauert lange.", translation: "The meeting takes a long time.",
    category: "Arbeit",
    note: "Adds -en. Feminine -ung noun. More formal than das Meeting (loanword).",
  },
  {
    singular: "Computer",     english: "computer",              article: "der", plural: "Computer",
    example: "Der Computer ist kaputt.", translation: "The computer is broken.",
    category: "Arbeit",
    note: "No change — masculine loanwords ending in -er are unchanged in the plural.",
  },
  {
    singular: "Termin",       english: "appointment / deadline", article: "der", plural: "Termine",
    example: "Ich habe einen Termin.", translation: "I have an appointment.",
    category: "Arbeit",
    note: "Adds -e. Very common: einen Termin machen (to make an appointment).",
  },
  {
    singular: "Projekt",      english: "project",               article: "das", plural: "Projekte",
    example: "Das Projekt ist fertig.", translation: "The project is finished.",
    category: "Arbeit",
    note: "Adds -e. International loanword — same root as the English word.",
  },
  {
    singular: "Urlaub",       english: "holiday / vacation",    article: "der", plural: "Urlaube",
    example: "Ich fahre in den Urlaub.", translation: "I am going on holiday.",
    category: "Arbeit",
    note: "Adds -e. Im Urlaub sein (to be on holiday). Usually used in the singular: Ich mache Urlaub.",
  },
  {
    singular: "Stelle",       english: "job / position",        article: "die", plural: "Stellen",
    example: "Ich suche eine neue Stelle.", translation: "I am looking for a new job.",
    category: "Arbeit",
    note: "Adds -n. Eine Stelle suchen means to look for a job. Distinct from der Job (casual work).",
  },
  {
    singular: "E-Mail",       english: "email",                 article: "die", plural: "E-Mails",
    example: "Die E-Mail ist wichtig.", translation: "The email is important.",
    category: "Arbeit",
    note: "Adds -s. Always feminine in German: eine E-Mail schreiben (to write an email).",
  },
  {
    singular: "Vertrag",      english: "contract",              article: "der", plural: "Verträge",
    example: "Ich unterschreibe den Vertrag.", translation: "I am signing the contract.",
    category: "Arbeit",
    note: "Umlaut + -e. Einen Vertrag unterschreiben (to sign a contract).",
  },

  // ── Freizeit ───────────────────────────────────────────────────────────────
  {
    singular: "Hobby",        english: "hobby",                 article: "das", plural: "Hobbys",
    example: "Mein Hobby ist Lesen.", translation: "My hobby is reading.",
    category: "Freizeit",
    note: "Adds -s — loanword plural. Was sind Ihre Hobbys? (What are your hobbies?) is a classic A1 question.",
  },
  {
    singular: "Film",         english: "film / movie",          article: "der", plural: "Filme",
    example: "Der Film ist spannend.", translation: "The film is exciting.",
    category: "Freizeit",
    note: "Adds -e. Einen Film anschauen (to watch a film). Der Lieblingsfilm is one's favourite film.",
  },
  {
    singular: "Kino",         english: "cinema",                article: "das", plural: "Kinos",
    example: "Wir gehen ins Kino.", translation: "We are going to the cinema.",
    category: "Freizeit",
    note: "Adds -s. Ins Kino gehen (to go to the cinema). Short for Kinematograph.",
  },
  {
    singular: "Musik",        english: "music",                 article: "die", plural: "—",
    example: "Die Musik ist laut.", translation: "The music is loud.",
    category: "Freizeit",
    note: "Uncountable. Ich höre Musik (I listen to music) is one of the most useful A1 sentences.",
  },
  {
    singular: "Konzert",      english: "concert",               article: "das", plural: "Konzerte",
    example: "Das Konzert beginnt um acht.", translation: "The concert starts at eight.",
    category: "Freizeit",
    note: "Adds -e. Ins Konzert gehen (to go to a concert). Also used for classical recitals.",
  },
  {
    singular: "Spiel",        english: "game",                  article: "das", plural: "Spiele",
    example: "Das Spiel macht Spaß.", translation: "The game is fun.",
    category: "Freizeit",
    note: "Adds -e. Covers board games, video games, and sports matches. Ein Spiel spielen (to play a game).",
  },
  {
    singular: "Reise",        english: "trip / journey",        article: "die", plural: "Reisen",
    example: "Die Reise ist lang.", translation: "The trip is long.",
    category: "Freizeit",
    note: "Adds -n. Eine Reise machen (to go on a trip). Gute Reise! is the German for 'have a good journey!'.",
  },
  {
    singular: "Fahrrad",      english: "bicycle",               article: "das", plural: "Fahrräder",
    example: "Ich fahre mit dem Fahrrad.", translation: "I ride my bicycle.",
    category: "Freizeit",
    note: "Umlaut + -er. Compound: fahren (to travel) + das Rad (wheel). Rad is also used informally.",
  },
  {
    singular: "Fußball",      english: "football / soccer",     article: "der", plural: "Fußbälle",
    example: "Der Fußball ist rund.", translation: "The football is round.",
    category: "Freizeit",
    note: "Umlaut + -e. Can mean the sport (kein Plural) or the ball itself: der Fußball → die Fußbälle.",
  },
  {
    singular: "Theater",      english: "theatre",               article: "das", plural: "Theater",
    example: "Das Theater ist alt.", translation: "The theatre is old.",
    category: "Freizeit",
    note: "No change. Ins Theater gehen (to go to the theatre). Also used idiomatically: Mach kein Theater! (Don't make a fuss!).",
  },
  {
    singular: "Party",        english: "party",                 article: "die", plural: "Partys",
    example: "Die Party ist toll.", translation: "The party is great.",
    category: "Freizeit",
    note: "Adds -s — loanword plural. Eine Party feiern (to throw a party).",
  },
  {
    singular: "Foto",         english: "photo",                 article: "das", plural: "Fotos",
    example: "Ich mache ein Foto.", translation: "I am taking a photo.",
    category: "Freizeit",
    note: "Adds -s. Short for das Fotograf. Ein Foto machen (to take a photo).",
  },
  {
    singular: "Verein",       english: "club / association",    article: "der", plural: "Vereine",
    example: "Ich bin in einem Verein.", translation: "I am in a club.",
    category: "Freizeit",
    note: "Adds -e. Central to German social life — sports clubs, choirs, community groups. Im Verein sein (to be in a club).",
  },
  {
    singular: "Museum",       english: "museum",                article: "das", plural: "Museen",
    example: "Das Museum ist interessant.", translation: "The museum is interesting.",
    category: "Freizeit",
    note: "Latin origin — replaces -um with -en in the plural, like Datum → Daten, Zentrum → Zentren.",
  },

  // ── Lebensmittel ───────────────────────────────────────────────────────────
  // (Das Lebensmittel-Alphabet — A bis Z)
  {
    singular: "Aprikose",     english: "apricot",               article: "die", plural: "Aprikosen",
    example: "Die Aprikose ist orange.", translation: "The apricot is orange.",
    category: "Lebensmittel",
    note: "Adds -n. A — from Arabic al-barqūq via Portuguese albricoque. Summer stone fruit, popular in jams.",
  },
  {
    singular: "Birne",        english: "pear",                  article: "die", plural: "Birnen",
    example: "Ich esse eine Birne.", translation: "I am eating a pear.",
    category: "Lebensmittel",
    note: "Adds -n. B — also colloquial for a light bulb: die Glühbirne (literally: glowing pear).",
  },
  {
    singular: "Chinakohl",    english: "Chinese cabbage / napa cabbage", article: "der", plural: "—",
    example: "Der Chinakohl ist frisch.", translation: "The Chinese cabbage is fresh.",
    category: "Lebensmittel",
    note: "Uncountable as a food. C — compound: China + der Kohl (cabbage). Very common in Asian cooking.",
  },
  {
    singular: "Dattel",       english: "date (fruit)",          article: "die", plural: "Datteln",
    example: "Die Dattel ist braun.", translation: "The date is brown.",
    category: "Lebensmittel",
    note: "Adds -n. D — typically sold and used in the plural: Ich kaufe Datteln. Comes from Greek dáktylos (finger).",
  },
  {
    singular: "Essig",        english: "vinegar",               article: "der", plural: "—",
    example: "Der Essig ist sauer.", translation: "The vinegar is sour.",
    category: "Lebensmittel",
    note: "Uncountable in everyday use. E — Essig und Öl (vinegar and oil) is a classic salad dressing. Technically plural die Essige exists for types of vinegar.",
  },
  {
    singular: "Feige",        english: "fig",                   article: "die", plural: "Feigen",
    example: "Die Feige ist reif.", translation: "The fig is ripe.",
    category: "Lebensmittel",
    note: "Adds -n. F — from Latin ficus. Feigenbaum is a fig tree. Used fresh or dried.",
  },
  {
    singular: "Gurke",        english: "cucumber",              article: "die", plural: "Gurken",
    example: "Die Gurke ist grün.", translation: "The cucumber is green.",
    category: "Lebensmittel",
    note: "Adds -n. G — die Gewürzgurke is a pickled gherkin, a classic German condiment.",
  },
  {
    singular: "Hackfleisch",  english: "ground / minced meat",  article: "das", plural: "—",
    example: "Ich kaufe Hackfleisch.", translation: "I am buying ground meat.",
    category: "Lebensmittel",
    note: "Uncountable. H — compound: hacken (to chop/mince) + Fleisch (meat). Sold by weight: 500 Gramm Hackfleisch, never pluralized.",
  },
  {
    singular: "Honig",        english: "honey",                 article: "der", plural: "—",
    example: "Der Honig ist süß.", translation: "The honey is sweet.",
    category: "Lebensmittel",
    note: "Uncountable. H — no umlaut: Honig, not Hönig. Plural die Honige exists for varieties (Waldhonig, Blütenhonig…).",
  },
  {
    singular: "Ingwer",       english: "ginger",                article: "der", plural: "—",
    example: "Der Ingwer ist scharf.", translation: "The ginger is spicy.",
    category: "Lebensmittel",
    note: "Uncountable. I — no change in the plural for types. Ingwertee (ginger tea) is very popular in German-speaking countries.",
  },
  {
    singular: "Kiwi",         english: "kiwi (fruit)",          article: "die", plural: "Kiwis",
    example: "Die Kiwi kommt aus Neuseeland.", translation: "The kiwi comes from New Zealand.",
    category: "Lebensmittel",
    note: "Adds -s — loanword plural. K — named after the kiwi bird from New Zealand. Officially die Kiwifrucht.",
  },
  {
    singular: "Knoblauch",    english: "garlic",                article: "der", plural: "—",
    example: "Der Knoblauch riecht stark.", translation: "The garlic smells strong.",
    category: "Lebensmittel",
    note: "Uncountable. K — eine Knoblauchzehe is a clove of garlic. Knoblauch is an old compound: Knob (ball) + Lauch (leek).",
  },
  {
    singular: "Koriander",    english: "coriander / cilantro",  article: "der", plural: "—",
    example: "Ich mag keinen Koriander.", translation: "I don't like coriander.",
    category: "Lebensmittel",
    note: "Uncountable. K — both the herb (leaf) and the spice (seed) are called Koriander.",
  },
  {
    singular: "Kartoffel",    english: "potato",                article: "die", plural: "Kartoffeln",
    example: "Die Kartoffel ist groß.", translation: "The potato is big.",
    category: "Lebensmittel",
    note: "Adds -n. K — essential German staple. From Italian tartufolo (little truffle). Synonyms: die Erdäpfel (southern Germany, Austria).",
  },
  {
    singular: "Lachs",        english: "salmon",                article: "der", plural: "Lachse",
    example: "Der Lachs ist rosa.", translation: "The salmon is pink.",
    category: "Lebensmittel",
    note: "Adds -e. L — very popular in German cuisine. Räucherlachs (smoked salmon) is a Frühstück classic.",
  },
  {
    singular: "Lauch",        english: "leek",                  article: "der", plural: "—",
    example: "Ich schneide den Lauch.", translation: "I am cutting the leek.",
    category: "Lebensmittel",
    note: "Uncountable in everyday use. L — ein Kilo Lauch (a kilo of leek), no plural marker even with a quantity. Der Knoblauch (garlic) shares this root.",
  },
  {
    singular: "Mehl",         english: "flour",                 article: "das", plural: "—",
    example: "Ich brauche Mehl für den Kuchen.", translation: "I need flour for the cake.",
    category: "Lebensmittel",
    note: "Uncountable in everyday use. M — Weizenmehl (wheat flour) is most common. Types add context: Mehl Type 405, 550…",
  },
  {
    singular: "Nudel",        english: "noodle / pasta",        article: "die", plural: "Nudeln",
    example: "Ich esse gern Nudeln.", translation: "I like eating noodles.",
    category: "Lebensmittel",
    note: "Adds -n. N — almost always used in the plural: Ich esse Nudeln. The singular die Nudel is rare.",
  },
  {
    singular: "Orange",       english: "orange (fruit)",        article: "die", plural: "Orangen",
    example: "Die Orange ist saftig.", translation: "The orange is juicy.",
    category: "Lebensmittel",
    note: "Adds -n. O — also called die Apfelsine in northern Germany. Pronounced oh-RAHN-zheh.",
  },
  {
    singular: "Pfeffer",      english: "pepper (spice)",        article: "der", plural: "—",
    example: "Der Pfeffer ist schwarz.", translation: "The pepper is black.",
    category: "Lebensmittel",
    note: "Uncountable. P — Salz und Pfeffer (salt and pepper) — the classic pair. Pfeffermühle is a pepper mill.",
  },
  {
    singular: "Petersilie",   english: "parsley",               article: "die", plural: "—",
    example: "Die Petersilie ist ein Kraut.", translation: "Parsley is a herb.",
    category: "Lebensmittel",
    note: "Uncountable. P — one of the most-used herbs in German cooking. From Greek petros (stone) + selinon (celery).",
  },
  {
    singular: "Peperoni",     english: "chili pepper",          article: "die", plural: "Peperoni",
    example: "Die Peperoni ist sehr scharf.", translation: "The chili is very spicy.",
    category: "Lebensmittel",
    note: "No change in plural. P — important: in German die Peperoni means hot chili, NOT bell pepper. Bell pepper is die Paprika.",
  },
  {
    singular: "Quitte",       english: "quince",                article: "die", plural: "Quitten",
    example: "Die Quitte ist hart.", translation: "The quince is hard.",
    category: "Lebensmittel",
    note: "Adds -n. Q — the only common German food word starting with Q. Too hard to eat raw; usually made into jam (Quittenmarmelade).",
  },
  {
    singular: "Reis",         english: "rice",                  article: "der", plural: "—",
    example: "Ich koche Reis.", translation: "I am cooking rice.",
    category: "Lebensmittel",
    note: "Uncountable. R — Ich koche Reis (I am cooking rice). Plural die Reissorten exists for varieties.",
  },
  {
    singular: "Salat",        english: "salad / lettuce",       article: "der", plural: "Salate",
    example: "Der Salat ist gesund.", translation: "The salad is healthy.",
    category: "Lebensmittel",
    note: "Adds -e. S — can mean the dish (ein gemischter Salat) or the leafy vegetable (ein Kopf Salat).",
  },
  {
    singular: "Speck",        english: "bacon",                 article: "der", plural: "—",
    example: "Der Speck ist salzig.", translation: "The bacon is salty.",
    category: "Lebensmittel",
    note: "Uncountable in everyday use. S — sold and used by weight, not by count: 100 Gramm Speck, no plural marker even in larger amounts.",
  },
  {
    singular: "Spinat",       english: "spinach",               article: "der", plural: "—",
    example: "Ich esse gern Spinat.", translation: "I like eating spinach.",
    category: "Lebensmittel",
    note: "Uncountable. S — from Persian aspanāḫ via Arabic. Popeye (Popeye der Seemann) made it famous!",
  },
  {
    singular: "Tomate",       english: "tomato",                article: "die", plural: "Tomaten",
    example: "Die Tomate ist rot.", translation: "The tomato is red.",
    category: "Lebensmittel",
    note: "Adds -n. T — from Nahuatl tomatl. Tomatensoße (tomato sauce) and Tomatensalat are staples.",
  },
  {
    singular: "Udon",         english: "udon noodles",          article: "die", plural: "Udon",
    example: "Ich esse Udon-Nudeln.", translation: "I am eating udon noodles.",
    category: "Lebensmittel",
    note: "No change. U — Japanese loanword, often used as die Udon-Nudeln. One of the few food words for U in German!",
  },
  {
    singular: "Vollkornbrot", english: "wholegrain bread",      article: "das", plural: "Vollkornbrote",
    example: "Ich esse Vollkornbrot zum Frühstück.", translation: "I eat wholegrain bread for breakfast.",
    category: "Lebensmittel",
    note: "Adds -e. V — compound: voll (whole) + Korn (grain) + Brot (bread). Germany has hundreds of bread varieties; Vollkornbrot is among the healthiest.",
  },
  {
    singular: "Xylit",        english: "xylitol",               article: "das", plural: "—",
    example: "Xylit ist ein Zuckerersatz.", translation: "Xylitol is a sugar substitute.",
    category: "Lebensmittel",
    note: "Uncountable. X — a natural sugar substitute found in birch bark. Often used in chewing gum. One of very few German food words starting with X!",
  },
  {
    singular: "Yuzu",         english: "yuzu (citrus fruit)",   article: "die", plural: "Yuzus",
    example: "Die Yuzu ist sauer.", translation: "The yuzu is sour.",
    category: "Lebensmittel",
    note: "Adds -s. Y — a Japanese citrus with a floral, tart flavour. Increasingly popular in European fine dining.",
  },
  {
    singular: "Zitrone",      english: "lemon",                 article: "die", plural: "Zitronen",
    example: "Die Zitrone ist gelb.", translation: "The lemon is yellow.",
    category: "Lebensmittel",
    note: "Adds -n. Z — from Arabic al-laymūn. Zitronensaft (lemon juice) and Zitronentee (lemon tea) are very common.",
  },
  {
    singular: "Zucker",       english: "sugar",                 article: "der", plural: "—",
    example: "Ich nehme Zucker in den Kaffee.", translation: "I take sugar in my coffee.",
    category: "Lebensmittel",
    note: "Uncountable. Z — Zucker und Salz (sugar and salt) are paired in many recipes. Plural die Zucker exists only for chemistry/types of sugar.",
  },
  {
    singular: "Zwiebel",      english: "onion",                 article: "die", plural: "Zwiebeln",
    example: "Die Zwiebel ist weiß.", translation: "The onion is white.",
    category: "Lebensmittel",
    note: "Adds -n. Z — from Latin cepa duplex (double onion). Zwiebelsuppe (onion soup) and Zwiebelkuchen (onion tart) are German classics.",
  },
  {
    singular: "Geschmack",    english: "taste / flavour",       article: "der", plural: "Geschmäcke",
    example: "Der Kuchen hat einen süßen Geschmack.", translation: "The cake has a sweet taste.",
    category: "Lebensmittel",
    note: "Umlaut + -e. Der Geschmack von Schokolade (the taste of chocolate). Also used abstractly: Geschmackssache (a matter of taste).",
  },

  // ── Geografie ──────────────────────────────────────────────────────────────
  {
    singular: "Berg",         english: "mountain",              article: "der", plural: "Berge",
    example: "Der Berg ist hoch.", translation: "The mountain is high.",
    category: "Geografie",
    note: "Adds -e. No umlaut — a regular masculine one-syllable noun. In die Berge fahren (to go to the mountains).",
  },
  {
    singular: "Fluss",        english: "river",                 article: "der", plural: "Flüsse",
    example: "Der Fluss ist breit.", translation: "The river is wide.",
    category: "Geografie",
    note: "Umlaut + -e. Vowel -u- becomes -ü-. Der Rhein and die Donau are two of Europe's major Flüsse.",
  },
  {
    singular: "Hauptstadt",   english: "capital (city)",        article: "die", plural: "Hauptstädte",
    example: "Berlin ist die Hauptstadt.", translation: "Berlin is the capital.",
    category: "Geografie",
    note: "Umlaut + -e. Compound: Haupt- (main/head) + die Stadt (city), which follows the same Stadt → Städte pattern.",
  },
  {
    singular: "Land",         english: "country",               article: "das", plural: "Länder",
    example: "Portugal ist ein schönes Land.", translation: "Portugal is a beautiful country.",
    category: "Geografie",
    note: "Umlaut + -er. Aus welchem Land kommen Sie? is a key A1 question. Also means 'state' within Germany (Bundesland).",
  },
  {
    singular: "Dorf",         english: "village",               article: "das", plural: "Dörfer",
    example: "Das Dorf ist klein.", translation: "The village is small.",
    category: "Geografie",
    note: "Umlaut + -er. Same pattern as Land → Länder, Haus → Häuser. Auf dem Dorf means 'in the countryside.'",
  },
  {
    singular: "Stadt",        english: "city / town",           article: "die", plural: "Städte",
    example: "Die Stadt ist groß.", translation: "The city is big.",
    category: "Geografie",
    note: "Umlaut + -e. In die Stadt gehen (to go into town) is common everyday phrasing.",
  },
  {
    singular: "See",          english: "lake",                  article: "der", plural: "Seen",
    example: "Der See ist tief.", translation: "The lake is deep.",
    category: "Geografie",
    note: "Adds -n. Watch the gender switch: der See (lake) vs. die See (sea) — same word, different meaning and article!",
  },
  {
    singular: "Insel",        english: "island",                article: "die", plural: "Inseln",
    example: "Die Insel liegt im Meer.", translation: "The island lies in the sea.",
    category: "Geografie",
    note: "Adds -n. Masculine/feminine -el nouns are mixed: dieser one takes -n, unlike der Schlüssel which stays unchanged.",
  },
  {
    singular: "Wald",         english: "forest / woods",        article: "der", plural: "Wälder",
    example: "Der Wald ist dunkel.", translation: "The forest is dark.",
    category: "Geografie",
    note: "Umlaut + -er. In den Wald gehen (to go into the forest). The Black Forest is der Schwarzwald.",
  },
  {
    singular: "Tal",          english: "valley",                article: "das", plural: "Täler",
    example: "Das Tal ist grün.", translation: "The valley is green.",
    category: "Geografie",
    note: "Umlaut + -er. Same pattern as Land → Länder. Found in many place names, e.g. Neandertal.",
  },
  {
    singular: "Grenze",       english: "border / boundary",     article: "die", plural: "Grenzen",
    example: "Die Grenze ist offen.", translation: "The border is open.",
    category: "Geografie",
    note: "Adds -n. An der Grenze (at the border). Also used figuratively: Grenzen setzen (to set boundaries).",
  },
  {
    singular: "Kontinent",    english: "continent",             article: "der", plural: "Kontinente",
    example: "Afrika ist ein Kontinent.", translation: "Africa is a continent.",
    category: "Geografie",
    note: "Adds -e. International loanword from Latin continens.",
  },
  {
    singular: "Straße",       english: "street / road",         article: "die", plural: "Straßen",
    example: "Die Straße ist lang.", translation: "The street is long.",
    category: "Geografie",
    note: "Adds -n. The most common word for a street — appears in nearly every German address.",
  },
  {
    singular: "Weg",          english: "way / path / road",     article: "der", plural: "Wege",
    example: "Der Weg führt zum See.", translation: "The path leads to the lake.",
    category: "Geografie",
    note: "Adds -e. Used for paths, routes, and directions: Welcher Weg führt zum Bahnhof? (Which way leads to the station?)",
  },
  {
    singular: "Gasse",        english: "alley / lane",          article: "die", plural: "Gassen",
    example: "Die Gasse ist eng.", translation: "The alley is narrow.",
    category: "Geografie",
    note: "Adds -n. A narrow street, common in old town centers (Altstadt). Common in Swiss and Austrian street names.",
  },
  {
    singular: "Allee",        english: "avenue",                article: "die", plural: "Alleen",
    example: "Die Allee hat viele Bäume.", translation: "The avenue has many trees.",
    category: "Geografie",
    note: "Adds -n. Borrowed from French allée — typically a wide, tree-lined street or boulevard.",
  },

  // ── Alltag ─────────────────────────────────────────────────────────────────
  {
    singular: "Abkürzung",    english: "abbreviation / shortcut", article: "die", plural: "Abkürzungen",
    example: "Ich kenne eine Abkürzung.", translation: "I know a shortcut.",
    category: "Alltag",
    note: "Adds -en. Feminine -ung noun. Has two meanings: a shortened word/phrase, or a shorter physical route.",
  },
  {
    singular: "Unfall",       english: "accident",               article: "der", plural: "Unfälle",
    example: "Der Unfall war schlimm.", translation: "The accident was bad.",
    category: "Alltag",
    note: "Umlaut + -e. Einen Unfall haben (to have an accident). Compound: un- (negative prefix) + der Fall (fall/case).",
  },

  // ── Mengen & Einheiten ─────────────────────────────────────────────────────
  {
    singular: "Pfund",        english: "pound (unit of weight)", article: "das", plural: "Pfund",
    example: "Ich kaufe ein Pfund Butter.", translation: "I am buying a pound of butter.",
    category: "Mengen & Einheiten",
    note: "No change in plural. After a number, the unit stays unchanged: ein Pfund Brot, zwei Pfund Butter — not 'zwei Pfunde.'",
  },
  {
    singular: "Kilo",         english: "kilo / kilogram",        article: "das", plural: "Kilo",
    example: "Ich brauche ein Kilo Kartoffeln.", translation: "I need a kilo of potatoes.",
    category: "Mengen & Einheiten",
    note: "Usually unchanged after a number: ein Kilo Lauch, zwei Kilo Kartoffeln. The form Kilos exists but is less common in measurements.",
  },
  {
    singular: "Gramm",        english: "gram",                   article: "das", plural: "Gramm",
    example: "Ich möchte hundert Gramm Käse.", translation: "I would like a hundred grams of cheese.",
    category: "Mengen & Einheiten",
    note: "No change in plural. Almost always paired directly with a number and no article: 100 Gramm Speck, 250 Gramm Mehl.",
  },

  // ── Aus dem Unterricht / from class notes ────────────────────────────────────
  {
    singular: "Sitzungszimmer", english: "conference / meeting room", article: "das", plural: "Sitzungszimmer",
    example: "Die Besprechung ist im Sitzungszimmer.", translation: "The meeting is in the conference room.",
    category: "Arbeit",
    note: "From das Zimmer, so the gender is das (not die — die Sitzungszimmer is the plural). No change in the plural. Common in Switzerland; everyday alternative: der Besprechungsraum.",
  },
  {
    singular: "Bild",          english: "picture / image",         article: "das", plural: "Bilder",
    example: "Das Bild hängt an der Wand.", translation: "The picture hangs on the wall.",
    category: "Alltag",
    note: "-er ending, no umlaut: das Bild → die Bilder. Same plural pattern as Kind → Kinder.",
  },
  {
    singular: "Sonnenaufgang", english: "sunrise",                 article: "der", plural: "Sonnenaufgänge",
    example: "Der Sonnenaufgang ist schön.", translation: "The sunrise is beautiful.",
    category: "Geografie",
    note: "Umlaut + -e plural: a → ä. Opposite: der Sonnenuntergang (sunset). Compound of die Sonne + der Aufgang — the last part (Aufgang, masc.) fixes the gender.",
  },

  // ── Zeit ─────────────────────────────────────────────────────────────────────
  {
    singular: "Tag",       english: "day",                  article: "der", plural: "Tage",
    example: "Heute ist ein schöner Tag.", translation: "Today is a beautiful day.",
    category: "Zeit",
    note: "Parts of the day are mostly masculine: der Morgen, der Mittag, der Abend — but die Nacht. Guten Tag!",
  },
  {
    singular: "Woche",     english: "week",                 article: "die", plural: "Wochen",
    example: "Die Woche hat sieben Tage.", translation: "The week has seven days.",
    category: "Zeit",
    note: "Regular -n plural. diese Woche = this week, nächste Woche = next week.",
  },
  {
    singular: "Monat",     english: "month",                article: "der", plural: "Monate",
    example: "Der Monat hat dreißig Tage.", translation: "The month has thirty days.",
    category: "Zeit",
    note: "-e plural, no umlaut. im Monat / dieser Monat.",
  },
  {
    singular: "Jahr",      english: "year",                 article: "das", plural: "Jahre",
    example: "Das Jahr hat zwölf Monate.", translation: "The year has twelve months.",
    category: "Zeit",
    note: "-e plural. dieses Jahr = this year; Ich bin … Jahre alt.",
  },
  {
    singular: "Stunde",    english: "hour",                 article: "die", plural: "Stunden",
    example: "Die Stunde hat sechzig Minuten.", translation: "The hour has sixty minutes.",
    category: "Zeit",
    note: "-n plural. eine Stunde = an hour. Don't confuse with die Uhr (clock / o'clock).",
  },
  {
    singular: "Minute",    english: "minute",               article: "die", plural: "Minuten",
    example: "Eine Minute hat sechzig Sekunden.", translation: "A minute has sixty seconds.",
    category: "Zeit",
    note: "-n plural. fünf Minuten. Same pattern as Stunde, Woche.",
  },
  {
    singular: "Morgen",    english: "morning",              article: "der", plural: "Morgen",
    example: "Am Morgen trinke ich Kaffee.", translation: "In the morning I drink coffee.",
    category: "Zeit",
    note: "No change in the plural (der Morgen → die Morgen). am Morgen = in the morning. Note: lowercase morgen = tomorrow.",
  },
  {
    singular: "Abend",     english: "evening",              article: "der", plural: "Abende",
    example: "Am Abend lese ich ein Buch.", translation: "In the evening I read a book.",
    category: "Zeit",
    note: "-e plural. am Abend = in the evening; Guten Abend!",
  },
  {
    singular: "Nacht",     english: "night",                article: "die", plural: "Nächte",
    example: "In der Nacht schlafe ich.", translation: "At night I sleep.",
    category: "Zeit",
    note: "Umlaut + -e: a → ä. Feminine, unlike the masculine parts of the day. Gute Nacht!",
  },
  {
    singular: "Uhr",       english: "clock / o'clock",      article: "die", plural: "Uhren",
    example: "Die Uhr ist kaputt.", translation: "The clock is broken.",
    category: "Zeit",
    note: "-en plural. die Uhr = clock/watch; also 'o'clock': um drei Uhr. Wie viel Uhr ist es?",
  },
  {
    singular: "Zeit",      english: "time",                 article: "die", plural: "Zeiten",
    example: "Ich habe keine Zeit.", translation: "I have no time.",
    category: "Zeit",
    note: "-en plural, but often uncountable: Ich habe keine Zeit. See the phrase 'Zeit haben'.",
  },
];
